
version: '3'

services:

  # start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    restart: always
    env_file:
      - ./dev.env
    volumes:
        - postgres:/var/lib/postgresql/data

volumes:
  postgres: